version: "3.8"
services:
  mongo:
    container_name: mern-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  backend:
    container_name: mern-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - "./backend/.env"
    command: npm run start:dev
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-network
    environment:
      MONGO_URI: mongodb://mern-mongo:27017/alx_project

  frontend:
    container_name: mern-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - "./frontend/.env"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
